Migration to Python3.8
UbiquityRobotics/ubiquity_motor pull request #134
Opened 2021-06-01 16:41 UTC by tp4348

Migration of python files for Noetic distribution. 
Before merging, we should test on the real robot.

2021-06-01 17:02 UTC, rohbotics requested changes

2021-06-01 17:02 UTC, rohbotics commented on scripts/upgrade_firmware.py
> +#! /usr/bin/env python
Should be `#!/usr/bin/env python3`

2021-06-01 17:02 UTC, rohbotics commented on scripts/test_motor_board.py
> +import _thread
We should migrate to the new threading module instead of using the Python2 compat mode.

2021-06-01 17:02 UTC, rohbotics commented on scripts/test_pi_gpio.py
> +#!/usr/bin/env python
#!/usr/bin/env python3

2021-06-01 17:02 UTC, rohbotics commented on scripts/test_motor_board.py
> +#!/usr/bin/env python
#!/usr/bin/env python3

2021-06-02 07:05 UTC, tp4348 commented on scripts/test_pi_gpio.py
> +#!/usr/bin/env python
Make sense yaa, "scratch scratch"

2021-06-02 21:03 UTC, rohbotics requested changes
Couple more things I noticed.

Also someone needs to re-test everything on a real robot.

2021-06-02 21:03 UTC, rohbotics commented on scripts/upgrade_firmware.py
> +                      chr((len(self.out) / 0o256) % 256)]
I don't think these numbers should actually be octal. (1 is going to the same in either base, and the 256 didn't have a leading 0 in the original).

2021-06-02 21:03 UTC, rohbotics commented on scripts/upgrade_firmware.py
> +        if DEBUG: print("Checksum is", checksum, "LSB", (checksum / 0o001) % 256, "MSB", (checksum / 256) % 256)
Same octal comment here

2021-06-03 06:24 UTC, tp4348 commented
Applied mentioned changes. @GreTimotej do you have any cycles to test that?

2021-06-09 01:22 UTC, GreTimotej commented
Today I tested the made changes and I think everything works as it should.

2021-07-22 22:21 UTC, rohbotics approved these changes

2021-07-22 22:24 UTC, rohbotics commented
Fixed the conflicts, now merging this.

2021-07-22 22:25 UTC, merged