Update README.md
UbiquityRobotics/ubiquity_motor pull request #27
Opened 2017-06-24 07:46 UTC by davecrawley

Hi guys I am trying to put current knowledge in the documentation. I have also put in what I think are appropriate headers so that we can start to fill out the sections that we need on this one.

2017-06-24 08:02 UTC, jim-v commented on README.md
> +[insert ppa command here]
The PPA is not necessary; the package is in the main ROS repos.

2017-06-25 14:29 UTC, rohbotics requested changes

2017-06-25 14:29 UTC, rohbotics commented on README.md
> +[insert ppa command here]
Agree with @jim-v the ppa lines should be removed. They can be replaced by something like:

The packages are available from the OSRF build farm.  See the ROS installation instructions for more details http://wiki.ros.org/kinetic/Installation/Ubuntu.

2017-06-25 14:29 UTC, rohbotics commented on README.md
> +Known Issues
We should just refer to the issue tracker here.

2017-06-25 14:29 UTC, rohbotics commented on README.md
> +[to be completed]
I don't think that we need to have all these separate sections for running on every platform. All the configuration for the node is in magni_robot. If the robot that a customer is running is not a standard Magni, they are going to have to customize magni_robot anyway. 

In here we should simply have one line about how the configuration in magni_robot may need to be changed to support having a FTDI (/dev/ttyUSB0) or internal (/dev/ttyS0) serial port.

2017-06-25 14:29 UTC, rohbotics commented on README.md
> +Ubiquity motors motor controller has a connector that is designed to operate with FTDI USB-serial devices thus making it possible to add a USB to serial device on the robot and make it run over USB.
Let's not refer to specific hardware in here, the idea is that this node will interface with the motor control system on both Magni and Loki.

Rohan

2017-06-25 14:29 UTC, rohbotics commented on README.md
> +This is a Package that provides a ROS interface for the motors in UbiquityRobotics robots
Nit: Package should not be capitalized, and Ubiquity Robotics should be two words in text.

2017-06-26 05:05 UTC, davecrawley commented on README.md
> +[insert ppa command here]
Agree can you just change the text the way you want it?

2017-06-26 05:07 UTC, davecrawley commented on README.md
> +This is a Package that provides a ROS interface for the motors in UbiquityRobotics robots
Agree can you just change the text the way you want it?

2017-06-26 05:07 UTC, davecrawley commented on README.md
> +Ubiquity motors motor controller has a connector that is designed to operate with FTDI USB-serial devices thus making it possible to add a USB to serial device on the robot and make it run over USB.
Agree can you just change the text the way you want it?

2017-06-26 05:08 UTC, davecrawley commented on README.md
> +[to be completed]
Agree can you just change the text the way you want it?

2017-06-26 05:08 UTC, davecrawley commented on README.md
> +Known Issues
Agree can you just change the text the way you want it? Am I missing something here?

2017-07-17 03:48 UTC, merged