Publish battery voltage messages
UbiquityRobotics/ubiquity_motor pull request #29
Opened 2017-08-24 06:54 UTC by jim-v

Closes #12

2017-08-25 02:04 UTC, rohbotics commented on src/motor_hardware.cc
> +                    bstate.percentage = std::numeric_limits<float>::quiet_NaN();
Can we put in a dumb percentage that goes between 0-100% between 22-28 volts ?

2017-08-25 02:04 UTC, rohbotics approved these changes
Good, but see comments

2017-08-25 03:46 UTC, jim-v commented
@rohbotics, how is this?

2017-08-26 01:55 UTC, rohbotics requested changes

2017-08-26 01:55 UTC, rohbotics commented on src/motor_hardware.cc
> +                        bstate.percentage = std::max(0.0, 2.0 * (bstate.voltage - 18.0));
`bstate.percentage` should be between 0 and 1. `0.02 * (bstate.voltage - 18.0)` should make it work

2017-08-26 01:55 UTC, rohbotics commented on src/motor_hardware.cc
> +                        bstate.percentage = std::min(100.0, 12.0 + (bstate.voltage - 22.0) * 15.0);
Same issue, should be something like `std::min(1.0, 0.12 + (bstate.voltage - 22.0) * 0.15);`

2017-08-26 01:58 UTC, rohbotics commented on src/motor_hardware.cc
> +                        bstate.percentage = std::max(0.0, 2.0 * (bstate.voltage - 18.0));
Also I think our lower voltage (0% level) should be 20V. at 18 you are at 9V per battery which is pretty low.

2017-08-26 02:25 UTC, jim-v commented
@rohbotics, good point.  I made it a simple linear function with 20V -> 0 and 28V -> 1

2017-08-26 02:29 UTC, rohbotics requested changes

2017-08-26 02:29 UTC, rohbotics commented on src/motor_hardware.cc
> +                      bstate.percentage = 0.0;
Why use an if, when you could just use std::max(0.0, bstate.percentage), it would be cleaner I think.

2017-08-26 02:44 UTC, rohbotics approved these changes
LGTM

2017-08-26 02:53 UTC, merged