A workaround for issue 83.  Insert a delay prior to serial port setup
UbiquityRobotics/ubiquity_motor pull request #90
Opened 2020-06-22 21:08 UTC by mjstn

Inserts a 2 second ROS delay prior to serial port setup. 

Tests so far show this seems to avoid the issue where some OS components sets the serial port to 115200. The odd thing about the defect is stty still shows it as 38.4k but it is in fact 115.2k baud

I am generally against the 'just put a delay in' approach but it is estimated that the root cause here may be extremely complex to find and this bug is impacting a major account thus brute force workaround.  So if a kernel/OS expert wishes to really fix the defect, go for it and simply remove this delay.  Maybe keep the logs so you can see if something shows up between logs like after we init something shows up.  Sadly whatever is doing it is likely NOT going to show up in ros log and would be in an OS log somewhere but at least the timestamps from our logs would get you to the kernel log or perhaps OS log area of interest.

NOTE: This change needs a separate pull request.  Earlier I had formed a branch trying to do this but it had other changes.   So have made this branch and deleted other branch to clean things up.

2020-06-23 04:34 UTC, rohbotics requested changes

2020-06-23 04:34 UTC, rohbotics commented on src/motor_hardware.cc
> +    serialInitDelay.sleep();
You can directly sleep with `ros::Duration(2.0).sleep();`

2020-06-24 05:34 UTC, mjstn commented
Have completed and tested conversion to simpler delay. Thanks

2020-06-24 18:55 UTC, rohbotics approved these changes

2020-06-25 07:44 UTC, merged